---

name: 🐞 Bug Report
description: Report an issue to help the project improve.
title: '[Bug]: '
labels: ['type: bug']

assignees:
  - lotyp

body:
  - type: markdown
    attributes:
      value: 🐞 **Bug Report**

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: Please provide a clear and detailed description of what the bug is. This helps us understand the issue quickly and look for potential fixes.
      placeholder: Explain the bug in as much detail as possible...
    validations:
      required: true

  - type: textarea
    id: regression
    attributes:
      label: Is this a regression?
      description: |
        Was this functionality working in a previous version?
        If yes, please mention the last version in which it worked properly.
        Understanding regressions helps prioritize fixes.
      placeholder: Yes or No, and details about the last working version...
    validations:
      required: false

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: To Reproduce
      description: |
        'Please provide step-by-step instructions that reproduce the issue:
        1. Use x argument / navigate to...
        2. Fill this information...
        3. Go to...
        4. See error
      placeholder: Detailed steps to reproduce the bug...
    validations:
      required: true

  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description: |
        Describe what you expected to happen.
        Clear expectations help understand the gap between current and desired states.
      placeholder: What did you expect to happen instead of the bug?
    validations:
      required: true

  - type: textarea
    id: media
    attributes:
      label: Media prove
      description: If applicable, add screenshots or videos to better illustrate the issue. Visual aids can significantly aid in diagnosing problems quicker.
      placeholder: Upload files or paste links here...
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Your environment
      description: |
        Provide detailed information about your environment to help us replicate the issue:
        * OS: [e.g. Ubuntu]
        * PHP version: [e.g. 8.2.2]
        * Package version: [e.g. 1.0.0]
        * Any relevant environment details
      placeholder: List your environment details here...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Include any other context about the problem here, such as unusual system configurations, previous issues, or possible causes.
      placeholder: Any additional information that could help us resolve the issue...
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        📛 To ensure a smooth issue processing, please check if a similar bug report has already been submitted before creating a new one.
        We highly value your contributions, so please make sure to familiarize yourself with our repository's guidelines:
        - [Code of Conduct](https://github.com/llm-agents-php/agents/blob/master/.github/CODE_OF_CONDUCT.md)
        - [Contribution Guidelines](https://github.com/llm-agents-php/agents/blob/master/.github/CONTRIBUTING.md)

...
