---

blank_issues_enabled: true

contact_links:
  - name: Start a discussion or ask a question.
    url: https://github.com/llm-agents-php/.github/discussions
    about: Please ask and answer questions here.

...
